# Generated by Django 5.0.7 on 2024-07-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userslist_alter_category_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userslist_users',
            name='userslist',
        ),
        migrations.RemoveField(
            model_name='userslist_users',
            name='user',
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='UsersList',
        ),
        migrations.DeleteModel(
            name='UsersList_users',
        ),
    ]
